source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'driverStreamTest' do
    pod 'SnapKit', '~> 4.0.0'
    pod 'SQLite.swift', '~> 0.11.4'
    pod ‘Alamofire’, ‘~> 4.5’
    pod ‘SwiftyJSON’
end
